import pandas as pd
import os
from datetime import datetime

# Create sample data for demonstration
def create_sample_data():
    properties = [
        # Amsterdam (Netherlands)
        {"country": "NL", "city": "Amsterdam", "neighbourhood": "De Pijp", "price_eur": 350000, "size_m2": 65, "price_per_m2": 5385, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/nl/amsterdam/1", "listing_date": "2024-01-15", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Amsterdam", "neighbourhood": "Jordaan", "price_eur": 375000, "size_m2": 72, "price_per_m2": 5208, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/nl/amsterdam/2", "listing_date": "2024-01-20", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Amsterdam", "neighbourhood": "Oud-West", "price_eur": 320000, "size_m2": 58, "price_per_m2": 5517, "bedrooms": 1, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/nl/amsterdam/3", "listing_date": "2024-01-18", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Amsterdam", "neighbourhood": "Westerpark", "price_eur": 395000, "size_m2": 80, "price_per_m2": 4938, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/nl/amsterdam/4", "listing_date": "2024-01-22", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Amsterdam", "neighbourhood": "Canal Belt", "price_eur": 385000, "size_m2": 70, "price_per_m2": 5500, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/nl/amsterdam/5", "listing_date": "2024-01-25", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Rotterdam", "neighbourhood": "Feijenoord", "price_eur": 280000, "size_m2": 95, "price_per_m2": 2947, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/nl/rotterdam/1", "listing_date": "2024-01-16", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Rotterdam", "neighbourhood": "Charlois", "price_eur": 310000, "size_m2": 110, "price_per_m2": 2818, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/nl/rotterdam/2", "listing_date": "2024-01-19", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Rotterdam", "neighbourhood": "Delfshaven", "price_eur": 265000, "size_m2": 85, "price_per_m2": 3118, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/nl/rotterdam/3", "listing_date": "2024-01-21", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Rotterdam", "neighbourhood": "Hillegersberg", "price_eur": 295000, "size_m2": 100, "price_per_m2": 2950, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/nl/rotterdam/4", "listing_date": "2024-01-23", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "NL", "city": "Rotterdam", "neighbourhood": "Kralingen", "price_eur": 320000, "size_m2": 105, "price_per_m2": 3048, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/nl/rotterdam/5", "listing_date": "2024-01-26", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Madrid", "neighbourhood": "Malasa", "price_eur": 350000, "size_m2": 95, "price_per_m2": 3684, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/madrid/1", "listing_date": "2024-01-17", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Madrid", "neighbourhood": "Retiro", "price_eur": 380000, "size_m2": 88, "price_per_m2": 4318, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/madrid/2", "listing_date": "2024-01-19", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Madrid", "neighbourhood": "Salamanca", "price_eur": 395000, "size_m2": 92, "price_per_m2": 4293, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/madrid/3", "listing_date": "2024-01-21", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Madrid", "neighbourhood": "Gran Via", "price_eur": 340000, "size_m2": 78, "price_per_m2": 4359, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/madrid/4", "listing_date": "2024-01-24", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Madrid", "neighbourhood": "Chueca", "price_eur": 320000, "size_m2": 75, "price_per_m2": 4267, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/madrid/5", "listing_date": "2024-01-26", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Barcelona", "neighbourhood": "Eixample", "price_eur": 360000, "size_m2": 85, "price_per_m2": 4235, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/barcelona/1", "listing_date": "2024-01-15", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Barcelona", "neighbourhood": "Gothic Quarter", "price_eur": 375000, "size_m2": 80, "price_per_m2": 4688, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/barcelona/2", "listing_date": "2024-01-18", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Barcelona", "neighbourhood": "Gracia", "price_eur": 330000, "size_m2": 75, "price_per_m2": 4400, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/barcelona/3", "listing_date": "2024-01-20", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Barcelona", "neighbourhood": "Pedralbes", "price_eur": 390000, "size_m2": 110, "price_per_m2": 3545, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/es/barcelona/4", "listing_date": "2024-01-22", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Barcelona", "neighbourhood": "Sarrià", "price_eur": 350000, "size_m2": 95, "price_per_m2": 3684, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/es/barcelona/5", "listing_date": "2024-01-25", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Valencia", "neighbourhood": "Benimaclet", "price_eur": 250000, "size_m2": 110, "price_per_m2": 2273, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/es/valencia/1", "listing_date": "2024-01-14", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Valencia", "neighbourhood": "City of Arts and Sciences", "price_eur": 290000, "size_m2": 95, "price_per_m2": 3053, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/valencia/2", "listing_date": "2024-01-17", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Valencia", "neighbourhood": "Extamundi", "price_eur": 270000, "size_m2": 100, "price_per_m2": 2700, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/es/valencia/3", "listing_date": "2024-01-19", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Valencia", "neighbourhood": "Ruzafa", "price_eur": 280000, "size_m2": 85, "price_per_m2": 3294, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/es/valencia/4", "listing_date": "2024-01-21", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "ES", "city": "Valencia", "neighbourhood": "Patalavaca", "price_eur": 260000, "size_m2": 105, "price_per_m2": 2476, "bedrooms": 3, "bathrooms": 2.0, "property_type": "House", "listing_url": "https://homestra.com/es/valencia/5", "listing_date": "2024-01-23", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Lisbon", "neighbourhood": "Alfama", "price_eur": 300000, "size_m2": 75, "price_per_m2": 4000, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/lisbon/1", "listing_date": "2024-01-16", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Lisbon", "neighbourhood": "Belem", "price_eur": 320000, "size_m2": 82, "price_per_m2": 3902, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/lisbon/2", "listing_date": "2024-01-18", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Lisbon", "neighbourhood": "Chiado", "price_eur": 310000, "size_m2": 70, "price_per_m2": 4429, "bedrooms": 1, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/lisbon/3", "listing_date": "2024-01-20", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Lisbon", "neighbourhood": "Principe Real", "price_eur": 330000, "size_m2": 78, "price_per_m2": 4231, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/lisbon/4", "listing_date": "2024-01-22", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Lisbon", "neighbourhood": "Marvila", "price_eur": 280000, "size_m2": 88, "price_per_m2": 3182, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/lisbon/5", "listing_date": "2024-01-24", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Porto", "neighbourhood": "Ribeira", "price_eur": 250000, "size_m2": 70, "price_per_m2": 3571, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/porto/1", "listing_date": "2024-01-15", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Porto", "neighbourhood": "Miragaia", "price_eur": 270000, "size_m2": 80, "price_per_m2": 3375, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/porto/2", "listing_date": "2024-01-17", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Porto", "neighbourhood": "Vitoria", "price_eur": 260000, "size_m2": 75, "price_per_m2": 3467, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/porto/3", "listing_date": "2024-01-19", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Porto", "neighbourhood": "Mirage", "price_eur": 290000, "size_m2": 85, "price_per_m2": 3412, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/porto/4", "listing_date": "2024-01-21", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "PT", "city": "Porto", "neighbourhood": "Serralves", "price_eur": 280000, "size_m2": 80, "price_per_m2": 3500, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/pt/porto/5", "listing_date": "2024-01-23", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Paris", "neighbourhood": "Le Marais", "price_eur": 390000, "size_m2": 55, "price_per_m2": 7091, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/paris/1", "listing_date": "2024-01-14", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Paris", "neighbourhood": "Montmartre", "price_eur": 370000, "size_m2": 50, "price_per_m2": 7400, "bedrooms": 1, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/paris/2", "listing_date": "2024-01-16", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Paris", "neighbourhood": "Latin Quarter", "price_eur": 350000, "size_m2": 48, "price_per_m2": 7292, "bedrooms": 1, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/paris/3", "listing_date": "2024-01-18", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Paris", "neighbourhood": "Belleville", "price_eur": 320000, "size_m2": 52, "price_per_m2": 6154, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/paris/4", "listing_date": "2024-01-20", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Paris", "neighbourhood": "Bastille", "price_eur": 380000, "size_m2": 60, "price_per_m2": 6333, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/paris/5", "listing_date": "2024-01-22", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Lyon", "neighbourhood": "Vieux Lyon", "price_eur": 280000, "size_m2": 75, "price_per_m2": 3733, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/lyon/1", "listing_date": "2024-01-15", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Lyon", "neighbourhood": "Presqu'île", "price_eur": 300000, "size_m2": 82, "price_per_m2": 3659, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/lyon/2", "listing_date": "2024-01-17", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Lyon", "neighbourhood": "Croix-Rousse", "price_eur": 270000, "size_m2": 78, "price_per_m2": 3462, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/lyon/3", "listing_date": "2024-01-19", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Lyon", "neighbourhood": "Guillotière", "price_eur": 250000, "size_m2": 70, "price_per_m2": 3571, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/lyon/4", "listing_date": "2024-01-21", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "FR", "city": "Lyon", "neighbourhood": "Confluence", "price_eur": 310000, "size_m2": 88, "price_per_m2": 3523, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/fr/lyon/5", "listing_date": "2024-01-23", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Rome", "neighbourhood": "Centro Storico", "price_eur": 350000, "size_m2": 70, "price_per_m2": 5000, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/rome/1", "listing_date": "2024-01-14", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Rome", "neighbourhood": "Trevi", "price_eur": 380000, "size_m2": 75, "price_per_m2": 5067, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/rome/2", "listing_date": "2024-01-16", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Rome", "neighbourhood": "Campo de' Fiori", "price_eur": 360000, "size_m2": 68, "price_per_m2": 5294, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/rome/3", "listing_date": "2024-01-18", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Rome", "neighbourhood": "Testaccio", "price_eur": 310000, "size_m2": 72, "price_per_m2": 4306, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/rome/4", "listing_date": "2024-01-20", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Rome", "neighbourhood": "Trastevere", "price_eur": 340000, "size_m2": 70, "price_per_m2": 4857, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/rome/5", "listing_date": "2024-01-22", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Milan", "neighbourhood": "Duomo", "price_eur": 380000, "size_m2": 65, "price_per_m2": 5846, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/milan/1", "listing_date": "2024-01-15", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Milan", "neighbourhood": "Brera", "price_eur": 360000, "size_m2": 60, "price_per_m2": 6000, "bedrooms": 1, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/milan/2", "listing_date": "2024-01-17", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Milan", "neighbourhood": "Navigli", "price_eur": 340000, "size_m2": 70, "price_per_m2": 4857, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/milan/3", "listing_date": "2024-01-19", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Milan", "neighbourhood": "Lambrate", "price_eur": 300000, "size_m2": 75, "price_per_m2": 4000, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/milan/4", "listing_date": "2024-01-21", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "IT", "city": "Milan", "neighbourhood": "Garibaldi", "price_eur": 370000, "size_m2": 68, "price_per_m2": 5441, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/it/milan/5", "listing_date": "2024-01-23", "is_capital": False, "scrape_date": datetime.now().isoformat()},
        {"country": "DE", "city": "Berlin", "neighbourhood": "Mitte", "price_eur": 340000, "size_m2": 85, "price_per_m2": 4000, "bedrooms": 2, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/de/berlin/1", "listing_date": "2024-01-14", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "DE", "city": "Berlin", "neighbourhood": "Kreuzberg", "price_eur": 310000, "size_m2": 80, "price_per_m2": 3875, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/de/berlin/2", "listing_date": "2024-01-16", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "DE", "city": "Berlin", "neighbourhood": "Charlottenburg", "price_eur": 330000, "size_m2": 95, "price_per_m2": 3474, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/de/berlin/3", "listing_date": "2024-01-18", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "DE", "city": "Berlin", "neighbourhood": "Schoneberg", "price_eur": 295000, "size_m2": 88, "price_per_m2": 3352, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/de/berlin/4", "listing_date": "2024-01-20", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "DE", "city": "Berlin", "neighbourhood": "Friedrichshain", "price_eur": 280000, "size_m2": 78, "price_per_m2": 3590, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/de/berlin/5", "listing_date": "2024-01-22", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "GR", "city": "Athens", "neighbourhood": "Plaka", "price_eur": 240000, "size_m2": 95, "price_per_m2": 2526, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/gr/athens/1", "listing_date": "2024-01-15", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "GR", "city": "Athens", "neighbourhood": "Kolonaki", "price_eur": 280000, "size_m2": 105, "price_per_m2": 2667, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/gr/athens/2", "listing_date": "2024-01-17", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "GR", "city": "Athens", "neighbourhood": "Psyrri", "price_eur": 260000, "size_m2": 98, "price_per_m2": 2653, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/gr/athens/3", "listing_date": "2024-01-19", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "GR", "city": "Athens", "neighbourhood": "Ampelokipi", "price_eur": 270000, "size_m2": 102, "price_per_m2": 2647, "bedrooms": 3, "bathrooms": 2.0, "property_type": "Apartment", "listing_url": "https://homestra.com/gr/athens/4", "listing_date": "2024-01-21", "is_capital": True, "scrape_date": datetime.now().isoformat()},
        {"country": "GR", "city": "Athens", "neighbourhood": "Exarhia", "price_eur": 250000, "size_m2": 100, "price_per_m2": 2500, "bedrooms": 2, "bathrooms": 1.0, "property_type": "Apartment", "listing_url": "https://homestra.com/gr/athens/5", "listing_date": "2024-01-23", "is_capital": True, "scrape_date": datetime.now().isoformat()},
    ]
    
    return pd.DataFrame(properties)


if __name__ == "__main__":
    df = create_sample_data()
    os.makedirs("data", exist_ok=True)
    df.to_csv("data/homestra_properties_raw.csv", index=False)
    print(f"Created sample data with {len(df)} properties")
